### ISSUE TITLE
Known file types marked as unknown

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#11]
http://discmaster.textfiles.com/browse/10348/MACPOWER-1998-08.ISO.7z/MACPOWER-1998-08.ISO/mac/Shareware%20Paradise/P_%20POCKET/P_%20POCKET(68k).sit/P_%20POCKET(68k)

- Pickle'sPocket is a Macromedia Director executable (I think they called them projectors)
- ReadMe is a SimpleText document

Are these "unknown" because they are inside a .sit archive?

ps: this "Pickle's Pocket" is my latest amazing find, using contents search 🥇

**Comment by Sembiance** [comment]
The SimpleText document was not being detected due to it being in a .sit and dexvert wasn't assigning MacOS file types/creator codes to the output files. I've just updated dexvert to handle this.

As for the Macromedia Director executable, it's a Director 5 file which is a version I don't support yet in dexvert, it's on my To-Do list :)

I'll see about maybe getting Director 5 support working sooner rather than later, then after that get Discmaster to reprocess this item (and maybe other Mac CDs too) to pick up the new dexvert support.

**Comment by gingerbeardman** [comment]
No rush with the Director 5 support, this issue was more about unknown items inside archives.

Feel free to close.

**Comment by Sembiance** [comment]
> BTW I've recently added some discs to my page on IA, but there will be a new big upload in the next month or so.

Awesome. Ping me after you've uploaded the next batc and I'll make sure Discmaster injests them in a timely fashion. By the way, just signed up for your patreon to help support your preservation efforts, it's important work!

**Comment by gingerbeardman** [comment]
Thank you!

**Comment by Sembiance** [comment]
Both of these things are fixed in discmaster 2. The Director 5 files are identified & supported and contents extracted from them and mac file types/creators are utilized to help identify files and convert them properly so the simpletext file is handled correctly too.

**Comment by gingerbeardman** [comment]
Double awesome!
