### ISSUE TITLE
Searching with max file size limit is slow

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#12]
Compare

with
- http://discmaster.textfiles.com/search?q=%22nabu+network%22&qfields=filename&qfields=ext&qfields=content&sizeMax=1MB

without
- http://discmaster.textfiles.com/search?q=%22nabu+network%22&qfields=filename&qfields=ext&qfields=content

**Comment by Sembiance** [comment]
Thanks for the report. Yah, that's odd. Not sure why the search engine being used (Typesense) is performing this way.  I've reached out to the developers of the search engine to see if there is some improvements that can be made either to the search engine itself or the schema/query that Discmaster is using.

**Comment by Sembiance** [comment]
I heard back from the search engine devs. The slowness is because the filtering (max size limit) takes place before the query and numerical filtering is slow. Improving this type of query is something they want to improve soon and is on their performance improvement backlog (https://github.com/typesense/typesense/issues/858).

I'll leave this issue open here until I have more news to share. It's likely to remain slow on Discmaster until Typesense can be improved to handle these queries better.

**Comment by gingerbeardman** [comment]
Thanks for chasing!

**Comment by Sembiance** [comment]
The DiscMaster project is changing hands and I am no longer associated with it. I will be mantaining the dexvert project (the conversion part) including releasing a 1.0 beta release soon, but issues related directly to the DiscMaster website are no longer something I have control over and thus are out of my purview.
