### ISSUE TITLE
Hex viewer?

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#16]
Not sure how feasible this is. 

Thought about it when trying to figure out how to view these PRN files. 

- http://discmaster.textfiles.com/browse/15974/Precos%204.97%20Computer%202000.iso/mac/Info/3Peripherals/EPSON/LIBRARY_MAC_P/LIBRARY

**Comment by Sembiance** [comment]
It's something I've thought about doing in the past but it fell by the wayside. The plan was to show the first 8k or so of bytes for files that were not able to be identified. It wouldn't have helped in this particular example, since it was identified but not handled correctly by dexvert (or mis-identified).

I think in the end I decided that for folks that are operating at that level, they would have their favorite hex editor they really like using and they would just download the files and open them up.

I'd like to leave this issue open though, it would still be useful to quick and easily see at a glance files.

**Comment by Sembiance** [comment]
The DiscMaster project is changing hands and I am no longer associated with it. I will be mantaining the dexvert project (the conversion part) including releasing a 1.0 beta release soon, but issues related directly to the DiscMaster website are no longer something I have control over and thus are out of my purview.

**Comment by Sembiance** [comment]
discmaster2 has a hex viewer
![screenshot_2024-04-05_22:00:50](https://github.com/Sembiance/dexvert/assets/81436/71be061f-508e-4dbf-be37-a23902b458d1)
