### ISSUE TITLE
Minor issues with MacJapanese

### ISSUE THREAD

**Issue by gingerbeardman** [Sembiance/dexvert#4]
Some text files are not recognised
- I can hunt more if that's useful?
- [example](http://discmaster.textfiles.com/view/9351/MACPEOPLE-1997-04-15.ISO.7z/MACPEOPLE-1997-04-15.ISO/%E4%B8%96%E7%95%8C%E3%81%AE%E3%82%B7%E3%82%A7%E3%82%A2%E3%82%A6%E3%82%A8%E3%82%A2/%E3%82%B2%E3%83%BC%E3%83%A0/%E3%81%B4%E3%82%88%E3%81%B4%E3%82%88%E3%81%94%E3%81%A3%E3%81%931.1/ReadMe1.1)

Some text files displayed with wrong encoding
- similar change needed as the recent HTML one?
- some text files will be MacRoman
- [example](http://discmaster.textfiles.com/view/9351/MACPEOPLE-1997-04-15.ISO.7z/MACPEOPLE-1997-04-15.ISO/PB1400%E3%83%96%E3%83%83%E3%82%AF%E3%82%AB%E3%83%90%E3%83%BC/%E3%81%8A%E8%AA%AD%E3%81%BF%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84)
- [example](http://discmaster.textfiles.com/view/9351/MACPEOPLE-1997-04-15.ISO.7z/MACPEOPLE-1997-04-15.ISO/%E4%BD%93%E9%A8%93%E7%89%88%E3%82%BD%E3%83%95%E3%83%88/%EF%BD%B8%EF%BE%97%EF%BE%98%EF%BD%BD%EF%BE%8E%EF%BD%B0%EF%BE%91%EF%BE%8D%EF%BE%9F%EF%BD%B0%EF%BD%BC%EF%BE%9E%202.0%E8%A9%95%E4%BE%A1%E7%89%8868K/%E5%A7%8B%E3%82%81%E3%81%AB%E3%81%8A%E8%AA%AD%E3%81%BF%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84)

**Comment by Sembiance** [comment]
Thanks for the report!

I have determined the cause of this. I use `hfsutils` to copy out the files and it is auto decoding `TEXT` and `ttro` files into MacRoman because it doesn't support MacJapanese encoding. I'll update my code to work around this limitation so that text files are properly decoded on MacJapanese CDs.
